@startuml
class ManagerOnlyFilter {
    - <<const>> ApiKeyHeader : string = "Api-Key"
    + ManagerOnlyFilter(apiKeyValidationService:IApiKeyValidationInterface)
    + <<async>> OnActionExecutionAsync(context:ActionExecutingContext, next:ActionExecutionDelegate) : Task
}
class ManagerOnlyAttribute {
    + ManagerOnlyAttribute()
}
IAsyncActionFilter <|-- ManagerOnlyFilter
ManagerOnlyFilter --> "_apiKeyValidationService" IApiKeyValidationInterface
TypeFilterAttribute <|-- ManagerOnlyAttribute
@enduml
