@startuml
class ItemType {
    + Id : int <<get>> <<set>>
    + Name : string? <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + IsDeleted : bool <<get>> <<set>> = false
    + Equals(other:ItemType?) : bool
}
ItemType o-> "CreatedAt" DateTime
ItemType o-> "UpdatedAt" DateTime
@enduml
