@startuml
!include .\\Program.puml
!include .\\Controllers\ClientsController.puml
!include .\\Controllers\InventoriesController.puml
!include .\\Controllers\ItemGroupController.puml
!include .\\Controllers\ItemLinesController.puml
!include .\\Controllers\ItemsController.puml
!include .\\Controllers\ItemTypesController.puml
!include .\\Controllers\LocationController.puml
!include .\\Controllers\OrderController.puml
!include .\\Controllers\ShipmentController.puml
!include .\\Controllers\SuppliersController.puml
' !include .\\Controllers\TestController.puml
!include .\\Controllers\TransfersController.puml
!include .\\Controllers\WarehousesController.puml
!include .\\Filters\AdminFilter.puml
!include .\\Filters\ManagerFilter.puml
!include .\\HelperFunctions\FieldCopyer.puml
!include .\\HelperFunctions\ModelValidator.puml
!include .\\HelperFunctions\ObjectCloner.puml
!include .\\HelperFunctions\TimeStamp.puml
!include .\\Interfaces\IApiKeyValidator.puml
!include .\\Interfaces\IClientStorage.puml
!include .\\Interfaces\IInventoryStorage.puml
!include .\\Interfaces\IItemGroupStorage.puml
!include .\\Interfaces\IItemLineStorage.puml
!include .\\Interfaces\IItemStorage.puml
!include .\\Interfaces\IItemTypeStorage.puml
!include .\\Interfaces\ILocationStorage.puml
!include .\\Interfaces\IOrderStograge.puml
!include .\\Interfaces\IShipmentStorage.puml
!include .\\Interfaces\ISupplierStorage.puml
!include .\\Interfaces\ITransferStorage.puml
!include .\\Interfaces\IWarehouseStorage.puml
' !include .\\Migrations\20250107093759_current1.puml
' !include .\\Migrations\20250107093759_current1.Designer.puml
' !include .\\Migrations\DatabaseContextModelSnapshot.puml
' !include .\\Models\ApiKeyModel.puml
' !include .\\Models\ClientModel.puml
' !include .\\Models\DatabaseContext.puml
' !include .\\Models\InventoriesModel.puml
' !include .\\Models\ItemGroupModel.puml
' !include .\\Models\ItemLinesModel.puml
' !include .\\Models\ItemModel.puml
' !include .\\Models\ItemTypesModel.puml
' !include .\\Models\LocationModel.puml
' !include .\\Models\OrderModel.puml
' !include .\\Models\ShipmentModel.puml
' !include .\\Models\SupplierModel.puml
' !include .\\Models\TransferModel.puml
' !include .\\Models\WarehouseModel.puml
!include .\\Services\ApiKeyValidateService.puml
!include .\\Services\ClientsDBStorage.puml
!include .\\Services\InventoriesDBStorage.puml
!include .\\Services\ItemGroupDBStorage.puml
!include .\\Services\ItemLinesDBStorage.puml
!include .\\Services\ItemsDBStorage.puml
!include .\\Services\ItemTypesDBStorage.puml
!include .\\Services\LocationDBStorage.puml
!include .\\Services\OrderDBStorage.puml
!include .\\Services\ShipmentDBStorage.puml
!include .\\Services\SuppliersDBStorage.puml
!include .\\Services\TransfersDBStorage.puml
!include .\\Services\WarehouseDBStorage.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\CargoHub.AssemblyInfo.puml
!include .\\obj\Debug\net8.0\CargoHub.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0\CargoHub.MvcApplicationPartsAssemblyInfo.puml
@enduml
