import http.client
import json
import pytest
from datetime import datetime
import time
from GlobalVariables import VERSION as URL
from GlobalVariables import HEADERS, BASE_URL, DATETIME_FORMAT, PORT


@pytest.fixture()
def connection() -> http.client.HTTPConnection:
    return http.client.HTTPConnection(BASE_URL, PORT)


def delete_test_location(connection: http.client.HTTPConnection, id=99999):
    # this test doesnt run standalone but is part of multiple tests
    # delete location with 'id': 99999
    connection.request('DELETE', f'{URL}/locations/{id}', headers=HEADERS)
    response = connection.getresponse()
    connection.close()
    return response.status


def get_posted_location(connection: http.client.HTTPConnection, id: int):
    # this test doesnt run standalone but is part of multiple tests
    connection.request('GET', f"{URL}/locations/{id}", headers=HEADERS)

    response = connection.getresponse()

    data = response.read()
    connection.close()
    return json.loads(data), response.status


def post_location(connection: http.client.HTTPConnection):
    # this test doesnt run standalone but is part of multiple tests
    body = {
        "WareHouseId": None,
        "Code": "Test_code",
        "Name": "Test_name",
    }
    json_body = json.dumps(body).encode('utf-8')

    # post location
    connection.request('POST', f'{URL}/locations/', headers=HEADERS, body=json_body)
    # get response
    response = connection.getresponse()
    # Read the response data to get the autogenerated id
    response_data = response.read().decode()
    response_json = json.loads(response_data)
    location_id = response_json.get('id')

    # assert that it has created
    assert response.status == 200
    # close connection
    response.close()
    body['id'] = location_id
    return body


def test_get_all_locations(connection: http.client.HTTPConnection):
    connection.request('GET', f'{URL}/locations', headers=HEADERS)

    response = connection.getresponse()
    assert response.status == 200
    data = json.loads(response.read())
    assert isinstance(data, list)
    connection.close()


def test_post_get_location(connection: http.client.HTTPConnection):
    body = post_location(connection)

    # get the body just posted
    connection.request('GET', f"{URL}/locations/{body['id']}", headers=HEADERS)

    response = connection.getresponse()
    assert response.status == 200

    data = response.read()
    connection.close()

    location_dict = json.loads(data)
    assert len(location_dict) == 6
    assert location_dict['id'] == body['id']
    assert location_dict['warehouse_id'] == body['warehouse_id']
    assert location_dict['code'] == body['code']
    assert location_dict['name'] == body['name']

    assert delete_test_location(connection, HEADERS) == 200


def test_put_location(connection: http.client.HTTPConnection):
    body = post_location(connection)

    # adjust locaton and PUT it
    body['code'] = 'changed_code'
    json_body = json.dumps(body).encode('utf-8')
    connection.request('PUT', f"{URL}/locations/{body['id']}", headers=HEADERS, body=json_body)
    connection.close()

    # GET adjusted location
    # get the body just posted
    connection.request('GET', f"{URL}/locations/{body['id']}", headers=HEADERS)

    response = connection.getresponse()
    assert response.status == 200

    data = response.read()
    connection.close()

    location_dict = json.loads(data)
    assert len(location_dict) == 6
    assert location_dict['id'] == body['id']
    assert location_dict['warehouse_id'] == body['warehouse_id']
    assert location_dict['code'] == body['code']
    assert location_dict['name'] == body['name']

    assert delete_test_location(connection, HEADERS) == 200


def test_delete_location(connection: http.client.HTTPConnection):
    # post location
    body = post_location(connection)
    # delte location
    assert delete_test_location(connection, HEADERS) == 200


def test_delte_location_with_wrong_id(connection: http.client.HTTPConnection):
    # trying to delete something that doesnt exist should return 404 not found
    assert delete_test_location(connection, id=99999999999999999999999) == 404


def test_get_with_wrong_id(connection: http.client.HTTPConnection):
    location_dict, status_code = get_posted_location(connection, 9999999999999999999999999999999999999)
    # trying to get something that doesnt exist should return 404 not found
    assert status_code == 404


def check_time_string_format(connection, date_string):
    # this test will fail: the datimestring being written is in the wrong format
    try:
        # Attempt to parse with the expected format
        # the correct format is taken from the existing objects in locations.json
        datetime.strptime(date_string, DATETIME_FORMAT)
        return True
    except BaseException:
        # if it breaks clean up the file
        delete_test_location(connection)
        return False


def test_created_at(connection: http.client.HTTPConnection):
    # created at is empty in the body that gets posted
    body = post_location(connection)
    location_dict, status_code = get_posted_location(connection, body['id'])
    assert status_code == 200

    assert location_dict["created_at"] != ""

    # assert that the created at is in the right format
    assert check_time_string_format(
        connection, location_dict["created_at"]), f"Datetime fromat incorrect: {
        location_dict['created_at']}"

    # turn string into datetime obj
    read_date_obj = datetime.strptime(location_dict["created_at"], DATETIME_FORMAT)
    current_time_obj = datetime.now()

    # make sure time is accurate by minutes
    assert read_date_obj.year == current_time_obj.year
    assert read_date_obj.month == current_time_obj.month
    assert read_date_obj.day == current_time_obj.day
    assert read_date_obj.hour == current_time_obj.hour
    assert read_date_obj.minute == current_time_obj.minute

    assert delete_test_location(connection) == 200


def test_updated_at(connection: http.client.HTTPConnection):
    # created at is empty in the body that gets posted
    body = post_location(connection, HEADERS)

    # wait one seconds so the created object will not be the same as the updated
    time.sleep(2)
    # update te location
    body['code'] = 'changed_code'
    json_body = json.dumps(body).encode('utf-8')
    connection.request('PUT', f"{URL}/locations/{body['id']}", headers=HEADERS, body=json_body)
    connection.close()

    # get the location ad check if updated_at is empty
    location_dict, status_code = get_posted_location(connection, body['id'])
    assert status_code == 200
    assert location_dict["updated_at"] != ""

    # assert that the created at is in the right format
    assert check_time_string_format(
        connection, location_dict["updated_at"]), f"Datetime fromat incorrect: {
        location_dict['updated_at']}"

    # turn string into datetime obj
    read_date_obj = datetime.strptime(location_dict["updated_at"], DATETIME_FORMAT)
    current_time_obj = datetime.now()

    # make sure time is accurate by minutes
    assert read_date_obj.year == current_time_obj.year
    assert read_date_obj.month == current_time_obj.month
    assert read_date_obj.day == current_time_obj.day
    assert read_date_obj.hour == current_time_obj.hour
    assert read_date_obj.minute == current_time_obj.minute

    # make sure the created_at and updated_at are not the same
    assert location_dict["updated_at"] != location_dict["created_at"]

    delete_test_location(connection)
