# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with Coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --verbosity normal
    - name: Check Coverage Report
      run: |
        if [ -s TestProject1/TestResults/*/coverage.cobertura.xml ]; then
          echo "Coverage report generated successfully."
        else
          echo "Coverage report is empty or not generated."
          exit 1
        fi
    - name: Check Coverage Report
      run: |
        if [ -s TestProject1/TestResults/*/coverage.cobertura.xml ]; then
          echo "Coverage report generated successfully."
        else
          echo "Coverage report is empty or not generated."
          exit 1
        fi
    - name: Extract Coverage Percentage (PowerShell)
      id: coverage
      shell: pwsh
      run: |
        $xmlPath = Get-ChildItem -Path TestProject1/TestResults/*/coverage.cobertura.xml
        [xml]$xml = Get-Content $xmlPath.FullName
    
        # Extract line-rate from the <package> element
        $lineRate = [double]$xml.coverage.packages.package[0].'@line-rate'
    
        Write-Host "Line Coverage Rate: $lineRate"
      
        # Check if lineRate is set correctly
        if (-not $lineRate) {
          Write-Host "Line rate could not be extracted. Exiting."
          exit 1
        }
    
        # Store the line rate in the GitHub environment variable
        echo "line_rate=$lineRate" >> $GITHUB_ENV
    - name: Fail if Coverage is Below Threshold (PowerShell)
      shell: pwsh
      run: |
        # Ensure line_rate is correctly set from the environment
        $line_rate = [double]$env:line_rate
      
        Write-Host "Current Coverage Rate: $line_rate" # Debug line
      
        if ($line_rate -lt 0.70) {
            Write-Host "Code coverage is below the threshold of 70%."
            Write-Host "Current coverage is $line_rate"
            exit 1
        } else {
          Write-Host "Code coverage is acceptable: $line_rate"
        }