# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Run Tests with Coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
    - name: Check Code Coverage
      run: |
        # Generate the coverage report in Cobertura format
        reportgenerator -reports:TestResults/*/coverage.cobertura.xml -targetdir:coverageReport -reporttypes:Html

        # Check the coverage percentage
        coverage=$(grep -oP '(?<=<line-rate>)[0-9.]+(?=</line-rate>)' coverageReport/* | awk '{sum+=$1} END {print sum/NR100}')
        echo "Code Coverage: $coverage%"

        # Check if coverage is below the threshold (70%)
        if (( $(echo "$coverage < 70" | bc -l) )); then
          echo "Code coverage is below 70%!"
          exit 1
        fi
        
    - name: Store Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverageReport/
